### ISSUE TITLE
failure to build

### ISSUE THREAD

**Issue by zbikk** [EasyRPG/Editor#218] opened 2023-10-06 14:58 UTC
![image](https://github.com/EasyRPG/Editor/assets/145393776/10513d46-3ea1-4867-98d9-4cd8dfdbbf1c)

(screenshot because pasting the output messes with the formatting)

**Comment by carstene1ns** [comment] 2023-10-06 21:57
Editor needs to be updated for liblcf 0.8, since these have been renamed:

https://github.com/EasyRPG/liblcf/commit/2a2e0d3900bfd11826626a8b28c7a6bf9bcb410c
https://github.com/EasyRPG/liblcf/commit/b6a280bc57b31fd3ebad3b55b5ae75a5bec46a61

**Comment by MolassesLover** [comment] 2023-10-23 21:56
I accidentally made a duplicate of this issue with commit [#220](https://github.com/EasyRPG/Editor/issues/220). Over on that issue I posted the latest commit of libclf at the time of [last Jenkins build](https://ci.easyrpg.org/job/editor-linux/98) build. For anyone looking, you can find it [here](https://github.com/EasyRPG/liblcf/tree/eb1d54bc20bde934893b1badb15efb2c4777f9ec). Building with that version of libclf installed should result in a successful build.

**Closed** 2024-04-27 20:54 UTC
Labels: Building
